version: "2"
linters:
  enable:
    - misspell
    - unconvert
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - all
        path: frontend/bindings
    paths:
      - .*_bind\.go$
      - frontend/bindings
      - frontend/.bindings-tmp
      - frontend/node_modules
      - build
      - dist
      - tools
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
