import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import {
  assertCLIversion,
  auditBindingsDirectory,
  auditFrontendBindingUsage,
  checkBindingsOwnership,
  compareBindingDirectories,
  createBindingsManifest,
  normalizeGeneratorExtraArgs,
  obfuscatedBindingsPath,
  parseCLIversion,
  parseWailsPin,
  resolvePinnedCLI,
  validateManifestMetadata,
} from "./lib/wails-bindings.mjs";

const pin = "v3.0.0-beta.8";
const generatedMarker = "// This file is automatically generated. DO NOT EDIT\n";
const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

async function readRepositoryFile(relative) {
  return (await readFile(path.join(repositoryRoot, ...relative.split("/")), "utf8"))
    .replaceAll("\r\n", "\n");
}

function taskBlock(source, name) {
  const marker = `  ${name}:\n`;
  const start = source.indexOf(marker);
  assert.notEqual(start, -1, `missing task ${name}`);
  const remainder = source.slice(start + marker.length);
  const nextOffset = remainder.search(/\n  \S/);
  const next = nextOffset === -1 ? -1 : start + marker.length + nextOffset;
  return source.slice(start, next === -1 ? source.length : next);
}

async function temporaryDirectory(prefix, callback) {
  const directory = await mkdtemp(path.join(os.tmpdir(), prefix));
  try {
    await callback(directory);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}

async function writeGenerated(directory, relative, source) {
  const full = path.join(directory, ...relative.split("/"));
  await mkdir(path.dirname(full), { recursive: true });
  await writeFile(full, source, "utf8");
}

async function writeRendererFixture(directory, source) {
  await writeGenerated(directory, "main.ts", source);
  await writeGenerated(
    directory,
    "lib/extensionHost/extensionHost.ts",
    [
      "TaskServiceBindings.RequestExecutionApproval(",
      "TaskServiceBindings.ExecuteApproved(",
      "TaskServiceBindings.Stop(",
    ].join("\n"),
  );
  await writeGenerated(
    directory,
    "stores/httpClient.ts",
    'import * as HTTPClientServiceBindings from "../../bindings/github.com/CuTeLiTTleBraids-Geek-studio/koyori-ide/services/httpclientservice.js";\n',
  );
}

test("go.mod pin parser rejects absent and floating Wails versions", () => {
  assert.equal(
    parseWailsPin(`module example\n\nrequire (\n\tgithub.com/wailsapp/wails/v3 ${pin}\n)\n`),
    pin,
  );
  assert.throws(() => parseWailsPin("module example\n"), /not pinned/);
  assert.throws(
    () => parseWailsPin("require (\n\tgithub.com/wailsapp/wails/v3 latest\n)\n"),
    /floating Wails version/,
  );
});

test("CLI probe reports missing and mismatched executables explicitly", () => {
  const missing = Object.assign(new Error("spawn failed"), { code: "ENOENT" });
  assert.throws(
    () => resolvePinnedCLI({
      pinnedVersion: pin,
      env: { WAILS3_BIN: "missing-wails3" },
      spawn: () => ({ error: missing }),
    }),
    /executable not found/,
  );
  assert.throws(
    () => resolvePinnedCLI({
      pinnedVersion: pin,
      env: { WAILS3_BIN: "wrong-wails3" },
      spawn: () => ({ status: 0, stdout: "v3.0.0-alpha2.117\n", stderr: "" }),
    }),
    /version mismatch.*beta\.8.*alpha2\.117/,
  );
  const runner = resolvePinnedCLI({
    pinnedVersion: pin,
    env: { WAILS3_BIN: "pinned-wails3" },
    spawn: () => ({ status: 0, stdout: `${pin}\n`, stderr: "" }),
  });
  assert.equal(runner.command, "pinned-wails3");
});

test("version parsing refuses output without an exact semantic version", () => {
  assert.equal(parseCLIversion(`Wails ${pin}`), pin);
  assert.equal(parseCLIversion("unknown"), null);
  assert.throws(() => assertCLIversion(pin, "unknown"), /did not report a version/);
});

test("build entry points cannot reuse unverified frontend assets", async () => {
  const windowsBuild = await readRepositoryFile("scripts/build-windows-gui.ps1");
  assert.doesNotMatch(windowsBuild, /SkipFrontend/);
  assert.match(windowsBuild, /\[CmdletBinding\(\)\]/);
  const generation = windowsBuild.indexOf("scripts\\generate-bindings.mjs");
  const frontendBuild = windowsBuild.indexOf("npm run build");
  const frontendFailure = windowsBuild.indexOf("Frontend production build failed");
  const backendBuild = windowsBuild.indexOf("& go build");
  assert.ok(generation >= 0 && generation < frontendBuild);
  assert.ok(frontendBuild < frontendFailure && frontendFailure < backendBuild);

  const dockerignore = await readRepositoryFile(".dockerignore");
  assert.match(dockerignore, /^frontend\/bindings\/$/m);
  assert.match(dockerignore, /^frontend\/dist\/$/m);
  assert.match(dockerignore, /^\.env$/m);
  assert.match(dockerignore, /^\.env\.\*$/m);
  assert.match(dockerignore, /^\.npmrc$/m);
  assert.match(dockerignore, /^\*\*\/\.npmrc$/m);
  assert.match(dockerignore, /^\*\.pem$/m);
  assert.match(dockerignore, /^\*\.pfx$/m);

  const dockerfile = await readRepositoryFile("build/docker/Dockerfile.server");
  const goImage = dockerfile.match(
    /^ARG GO_IMAGE=(golang:1\.25-alpine@sha256:[0-9a-f]{64})$/m,
  );
  assert.ok(
    goImage,
    "Dockerfile.server must declare a digest-pinned default GO_IMAGE",
  );
  const bindingsGo = dockerfile.match(
    /^FROM (golang:1\.25-alpine@sha256:[0-9a-f]{64}) AS bindings-go$/m,
  );
  assert.ok(
    bindingsGo,
    "Dockerfile.server bindings-go stage must use an exact SHA-256-pinned Go image",
  );
  assert.equal(
    bindingsGo[1],
    goImage[1],
    "Dockerfile.server bindings-go stage must match the declared GO_IMAGE digest",
  );
  assert.match(dockerfile, /^FROM node:20\.19-alpine@sha256:[0-9a-f]{64} AS frontend-builder$/m);
  assert.match(dockerfile, /^RUN cd frontend && npm ci --ignore-scripts && npm run build$/m);
  assert.match(
    dockerfile,
    /image reference is not digest-pinned/,
    "Dockerfile.server must reject mutable image overrides",
  );
  assert.match(
    dockerfile,
    /^COPY --from=frontend-builder \/app\/frontend\/dist \.\/frontend\/dist$/m,
  );

  const crossDockerfile = await readRepositoryFile("build/docker/Dockerfile.cross");
  assert.doesNotMatch(crossDockerfile, /! -d "frontend\/dist"/);
  assert.doesNotMatch(crossDockerfile, /host may have built it/i);
  assert.doesNotMatch(crossDockerfile, /npm install/);
  assert.match(crossDockerfile, /^ARG NODE_VERSION=22\.14\.0$/m);
  assert.match(crossDockerfile, /test "\$\(node --version\)" = "v\$\{NODE_VERSION\}"/);
  assert.match(crossDockerfile, /linux\/\$\{TARGET_GOARCH\} with CGO cannot use native gcc/);
  assert.match(crossDockerfile, /if \[ "\$TARGET_GOARCH" != "\$CONTAINER_GOARCH" \]; then[\s\S]*?exit 1/);
  const crossGenerate = crossDockerfile.indexOf("node scripts/generate-bindings.mjs");
  const crossInstall = crossDockerfile.indexOf("npm ci");
  const crossBuild = crossDockerfile.indexOf("npm run --ignore-scripts build");
  const crossCheck = crossDockerfile.indexOf("node scripts/check-bindings.mjs");
  const crossDist = crossDockerfile.indexOf("test -s frontend/dist/index.html");
  const crossHTTPClient = crossDockerfile.indexOf("node scripts/check-http-client-production.mjs");
  const crossGoBuild = crossDockerfile.indexOf('${COMPILER} -tags "$TAGS"');
  assert.ok(crossGenerate >= 0 && crossGenerate < crossInstall);
  assert.ok(crossInstall < crossBuild && crossBuild < crossCheck);
  assert.ok(crossCheck < crossDist && crossDist < crossHTTPClient && crossHTTPClient < crossGoBuild);

  const crossScript = await readRepositoryFile("build/scripts/wsl-cross-macos-desktop.sh");
  assert.doesNotMatch(crossScript, /docker image inspect wails-cross/);
  assert.doesNotMatch(crossScript, /SRC=\/mnt\/[a-z]\//i);
  assert.match(crossScript, /BASH_SOURCE\[0\]/);
  assert.match(crossScript, /KOYORI_IDE_SOURCE_DIR/);
  assert.match(crossScript, /docker build -t wails-cross/);

  const packageJson = JSON.parse(await readRepositoryFile("frontend/package.json"));
  assert.equal(packageJson.scripts.prebuild, "npm run bindings:generate");
  assert.equal(packageJson.scripts.postbuild, "node ../scripts/check-http-client-production.mjs");
  assert.equal(packageJson.scripts["bindings:generate"], "node ../scripts/generate-bindings.mjs");
});

test("release verifies the repository Wails pin before installing or building", async () => {
  const workflow = await readRepositoryFile(".github/workflows/release.yml");
  const ownershipGate = workflow.indexOf("node scripts/check-bindings-ownership.mjs");
  const pinGate = workflow.indexOf("node scripts/check-wails-pin.mjs");
  const generation = workflow.indexOf("node scripts/generate-bindings.mjs");
  const cliInstall = workflow.indexOf("go install github.com/wailsapp/wails/v3/cmd/wails3@");
  const build = workflow.indexOf("run: ${{ matrix.build_cmd }}");
  assert.ok(ownershipGate >= 0 && ownershipGate < generation);
  assert.ok(pinGate >= 0 && pinGate < cliInstall);
  assert.ok(cliInstall < build);
});

test("CI and package workflows verify untracked ownership before generation", async () => {
  for (const relative of [
    ".github/workflows/ci.yml",
    ".github/workflows/package.yml",
    ".github/workflows/release.yml",
    ".github/workflows/release-installers.yml",
  ]) {
    const workflow = await readRepositoryFile(relative);
    const ownership = workflow.indexOf("node scripts/check-bindings-ownership.mjs");
    const generation = workflow.indexOf("node scripts/generate-bindings.mjs");
    assert.ok(ownership >= 0 && ownership < generation, `${relative} ownership gate order`);
  }
  const packageWorkflow = await readRepositoryFile(".github/workflows/package.yml");
  // G-CI-09: one ownership gate per packaging platform job (macOS, Linux,
  // Windows). The assertion was written when only two jobs existed.
  assert.equal(
    packageWorkflow.match(/node scripts\/check-bindings-ownership\.mjs/g)?.length,
    3,
  );
});

test("Git ownership check fails closed and lists tracked bindings", () => {
  assert.deepEqual(
    checkBindingsOwnership({
      spawn: () => ({ status: 0, stdout: "", stderr: "" }),
    }),
    [],
  );
  assert.throws(
    () => checkBindingsOwnership({
      spawn: () => ({
        status: 0,
        stdout: "frontend/bindings/github.com/CuTeLiTTleBraids-Geek-studio/koyori-ide/services/fileservice.ts\n",
        stderr: "",
      }),
    }),
    /must remain untracked[\s\S]*fileservice\.ts/,
  );
  assert.throws(
    () => checkBindingsOwnership({
      spawn: () => ({ status: 128, stdout: "", stderr: "not a git repository" }),
    }),
    /git ls-files failed with exit 128.*not a git repository/,
  );
  assert.throws(
    () => checkBindingsOwnership({
      spawn: () => ({ error: { code: "ENOENT", message: "missing" } }),
    }),
    /cannot inspect Git ownership: executable not found/,
  );
});

test("low-level build and package tasks cannot bypass binding generation", async () => {
  const common = await readRepositoryFile("build/Taskfile.yml");
  for (const name of [
    "frontend:run",
    "frontend:run:npm",
    "frontend:run:yarn",
    "frontend:run:pnpm",
    "frontend:run:bun",
    "frontend:dev:npm",
    "frontend:dev:yarn",
    "frontend:dev:pnpm",
    "frontend:dev:bun",
  ]) {
    assert.match(taskBlock(common, name), /\n    internal: true\n/);
  }
  assert.match(taskBlock(common, "dev:frontend"), /- task: generate:bindings/);

  const android = await readRepositoryFile("build/android/Taskfile.yml");
  assert.match(taskBlock(android, "build"), /PRODUCTION:\n\s+ref: \.PRODUCTION/);
  const androidCompile = taskBlock(android, "compile:go:shared");
  assert.match(androidCompile, /\n    internal: true\n/);
  assert.match(androidCompile, /- task: common:build:frontend/);
  assert.match(androidCompile, /- task: generate:android:overlay/);
  assert.match(taskBlock(android, "compile:go:all-archs"), /\n    internal: true\n/);
  assert.match(taskBlock(android, "assemble:apk"), /eq \.PIPELINE_OWNER "android-run"/);
  assert.match(taskBlock(android, "assemble:apk:release"), /eq \.PIPELINE_OWNER "android-package"/);
  assert.match(taskBlock(android, "package"), /PIPELINE_OWNER: android-package/);
  assert.match(taskBlock(android, "package:fat"), /PIPELINE_OWNER: android-package/);
  assert.match(taskBlock(android, "run"), /PIPELINE_OWNER: android-run/);

  const darwin = await readRepositoryFile("build/darwin/Taskfile.yml");
  assert.match(taskBlock(darwin, "create:app:bundle"), /eq \.PIPELINE_OWNER "darwin-package"/);
  assert.match(taskBlock(darwin, "package"), /PIPELINE_OWNER: darwin-package/);
  assert.match(taskBlock(darwin, "package:universal"), /PIPELINE_OWNER: darwin-package/);

  const ios = await readRepositoryFile("build/ios/Taskfile.yml");
  assert.match(taskBlock(ios, "compile:ios:link"), /eq \.PIPELINE_OWNER "ios-package"/);
  assert.match(taskBlock(ios, "create:app:bundle"), /eq \.PIPELINE_OWNER "ios-package"/);
  assert.match(taskBlock(ios, "package"), /PIPELINE_OWNER: ios-package/);
  assert.match(taskBlock(ios, "compile:ios"), /PIPELINE_OWNER: ios-compile/);
  assert.match(taskBlock(ios, "xcode"), /- task: build/);
});

test("manifest metadata rejects wrong generator version and mixed ownership", () => {
  const manifest = {
    schemaVersion: 1,
    strategy: "tracked",
    generator: {
      module: "github.com/wailsapp/wails/v3",
      version: "v3.0.0-alpha2.117",
      flags: ["-clean=true", "-ts", "-i"],
    },
    files: { "a.ts": "hash" },
    exports: { "a.ts": ["Read"] },
  };
  const errors = validateManifestMetadata(manifest, pin).join("\n");
  assert.match(errors, /untracked generation strategy/);
  assert.match(errors, /does not match go\.mod/);
});

test("directory audit rejects missing, empty, stale, extra, FQN and forbidden exports", async () => {
  await temporaryDirectory("koyori-ide-bindings-unit-", async (directory) => {
    const relative = "github.com/CuTeLiTTleBraids-Geek-studio/koyori-ide/services/fileservice.ts";
    const clean = `${generatedMarker}export function ReadFile() { return $Call.ByID(1); }\n`;
    await writeGenerated(directory, relative, clean);
    const manifest = await createBindingsManifest(directory, pin);

    const missingErrors = await auditBindingsDirectory(path.join(directory, "absent"), manifest);
    assert.match(missingErrors.join("\n"), /missing bindings directory/);

    const empty = path.join(directory, "empty");
    await mkdir(empty);
    const emptyErrors = await auditBindingsDirectory(empty, manifest);
    assert.match(emptyErrors.join("\n"), /bindings directory is empty/);

    await writeGenerated(directory, relative, `${clean}// drift\n`);
    let errors = await auditBindingsDirectory(directory, manifest);
    assert.match(errors.join("\n"), /stale or modified generated file/);

    await writeGenerated(directory, relative, clean);
    await writeGenerated(directory, "unexpected.ts", generatedMarker);
    errors = await auditBindingsDirectory(directory, manifest);
    assert.match(errors.join("\n"), /unexpected generated file/);

    const byName = `${generatedMarker}export function ReadFile() { return $Call.ByName("bad.FQN"); }\n`;
    await rm(path.join(directory, "unexpected.ts"));
    await writeGenerated(directory, relative, byName);
    const byNameManifest = await createBindingsManifest(directory, pin);
    errors = await auditBindingsDirectory(directory, byNameManifest);
    assert.match(errors.join("\n"), /name-based FQN call/);

    const forbidden = `${generatedMarker}export function SetWorkspaceRoot() { return $Call.ByID(2); }\n`;
    await writeGenerated(directory, relative, forbidden);
    const forbiddenManifest = await createBindingsManifest(directory, pin);
    errors = await auditBindingsDirectory(directory, forbiddenManifest);
    assert.match(errors.join("\n"), /forbidden export SetWorkspaceRoot/);

    await writeGenerated(directory, relative, clean);
    const settingsRelative = "github.com/CuTeLiTTleBraids-Geek-studio/koyori-ide/services/settingsservice.ts";
    for (const method of [
      "GetSecret",
      "StoreSecret",
      "DeleteSecret",
      "GetExtensionSecret",
      "StoreExtensionSecret",
      "DeleteExtensionSecret",
    ]) {
      await writeGenerated(
        directory,
        settingsRelative,
        `${generatedMarker}export function ${method}() { return $Call.ByID(3); }\n`,
      );
      const secretManifest = await createBindingsManifest(directory, pin);
      errors = await auditBindingsDirectory(directory, secretManifest);
      assert.match(errors.join("\n"), new RegExp(`forbidden export ${method}`));
    }
  });
});

test("directory audit requires an exact service-module export whitelist", async () => {
  await temporaryDirectory("koyori-ide-bindings-exports-", async (directory) => {
    const fileService = "github.com/CuTeLiTTleBraids-Geek-studio/koyori-ide/services/fileservice.ts";
    const settingsService = "github.com/CuTeLiTTleBraids-Geek-studio/koyori-ide/services/settingsservice.ts";
    await writeGenerated(
      directory,
      fileService,
      `${generatedMarker}export function ReadFile() { return $Call.ByID(1); }\n`,
    );
    await writeGenerated(
      directory,
      settingsService,
      `${generatedMarker}export function LoadSettings() { return $Call.ByID(2); }\n`,
    );
    const manifest = await createBindingsManifest(directory, pin);

    delete manifest.exports[settingsService];
    let errors = await auditBindingsDirectory(directory, manifest);
    assert.match(errors.join("\n"), /missing from export whitelist.*settingsservice\.ts/);

    manifest.exports[settingsService] = ["LoadSettings"];
    manifest.exports["github.com/CuTeLiTTleBraids-Geek-studio/koyori-ide/services/phantomservice.ts"] = ["Read"];
    errors = await auditBindingsDirectory(directory, manifest);
    assert.match(errors.join("\n"), /phantom service module.*phantomservice\.ts/);
  });
});

test("renderer audit rejects manual IDs, FQNs, aliases, and dynamic runtime imports", async () => {
  await temporaryDirectory("koyori-ide-renderer-bindings-", async (directory) => {
    await writeRendererFixture(
      directory,
      'import { Events } from "@wailsio/runtime";\nEvents.On("ready", () => {});\n',
    );
    assert.deepEqual(await auditFrontendBindingUsage(directory), []);

    for (const source of [
      'import { Call as invoke } from "@wailsio/runtime";\ninvoke.ByID(123);\n',
      'import * as Runtime from "@wailsio/runtime";\nRuntime.Call["ByName"]("bad.FQN");\n',
      'const runtime = await import("@wailsio/runtime");\nruntime.Call["By" + "ID"](123);\n',
      '$Call.ByName("bad.FQN");\n',
    ]) {
      await writeRendererFixture(directory, source);
      const errors = await auditFrontendBindingUsage(directory);
      assert.match(errors.join("\n"), /renderer source bypasses generated bindings/);
    }

    await writeRendererFixture(directory, 'SetWorkspaceRoot("C:/forged");\n');
    const rootErrors = await auditFrontendBindingUsage(directory);
    assert.match(rootErrors.join("\n"), /hidden root setter/);

    for (const method of ["GetSecret", "StoreSecret", "DeleteSecret", "GetExtensionSecret", "StoreExtensionSecret", "DeleteExtensionSecret"]) {
      await writeRendererFixture(directory, `SettingsServiceBindings.${method}('ai-api-key');\n`);
      const secretErrors = await auditFrontendBindingUsage(directory);
      assert.match(secretErrors.join("\n"), /forbidden raw secret binding/);
    }

    await writeGenerated(
      directory,
      "stores/httpClient.ts",
      'const bindingPath = "../../bindings/github.com/CuTeLiTTleBraids-Geek-studio/koyori-ide/services/httpclientservice.js";\nawait import(/* @vite-ignore */ bindingPath);\n',
    );
    const httpClientErrors = await auditFrontendBindingUsage(directory);
    assert.match(httpClientErrors.join("\n"), /must statically import its generated binding/);
    assert.match(httpClientErrors.join("\n"), /contains a runtime binding loader/);
  });
});

test("obfuscated metadata has one explicit untracked owner", async () => {
  const normalized = normalizeGeneratorExtraArgs(["-obfuscated"]);
  assert.equal(normalized.obfuscated, true);
  assert.deepEqual(normalized.args.slice(-2), ["-obfuscated-output", repositoryRoot]);
  assert.equal(obfuscatedBindingsPath, path.join(repositoryRoot, "wails_obfuscated.gen.go"));
  assert.throws(
    () => normalizeGeneratorExtraArgs([
      "-obfuscated",
      "-obfuscated-output",
      path.join(repositoryRoot, "build"),
    ]),
    /must be generated in the repository root/,
  );
  const gitignore = await readRepositoryFile(".gitignore");
  assert.match(gitignore, /^\/wails_obfuscated\.gen\.go$/m);
});

test("failed runtime probe invalidates stale PASS evidence", async () => {
  await temporaryDirectory("koyori-ide-runtime-failure-", async (directory) => {
    const evidence = path.join(directory, "runtime-bindings.json");
    await writeFile(evidence, '{"status":"passed","stale":true}\n', "utf8");
    const missingCLI = path.join(directory, "missing-wails3.exe");
    const result = spawnSync(
      process.execPath,
      [path.join(repositoryRoot, "scripts", "wails-runtime-bindings.mjs")],
      {
        cwd: repositoryRoot,
        encoding: "utf8",
        env: {
          ...process.env,
          KOYORI_IDE_WAILS_BINDINGS_EVIDENCE_DIR: directory,
          WAILS3_BIN: missingCLI,
        },
      },
    );
    assert.notEqual(result.status, 0, `${result.stdout}\n${result.stderr}`);
    await assert.rejects(readFile(evidence, "utf8"), /ENOENT/);
    const failure = JSON.parse(await readFile(
      path.join(directory, "runtime-bindings.failure.json"),
      "utf8",
    ));
    assert.equal(failure.status, "failed");
    assert.match(failure.error, /executable not found/);
  });
});

test("fresh-directory comparison rejects generated dirty state", async () => {
  await temporaryDirectory("koyori-ide-bindings-left-", async (left) => {
    await temporaryDirectory("koyori-ide-bindings-right-", async (right) => {
      await writeGenerated(left, "service.ts", `${generatedMarker}left\n`);
      await writeGenerated(right, "service.ts", `${generatedMarker}right\n`);
      const errors = await compareBindingDirectories(left, right);
      assert.match(errors.join("\n"), /generated drift/);
    });
  });
});

test("test fixture hash is stable", () => {
  assert.equal(
    createHash("sha256").update(generatedMarker).digest("hex").length,
    64,
  );
});
