// 架构改进 B (prompt-1.md): 跨窗口事件总线与 store 边界。
//
// 边界约定：跨窗口（main ↔ AI companion window）通信用 Wails Events；窗口
// 内部状态用 reactive store。本模块是唯一的「事件 → store 动作」编排层，
// 在应用启动时调用 initCrossWindowSync() 一次性接线，teardownCrossWindowSync()
// 用于 HMR / 测试清理。
//
// 事件 → store 映射表（全仓库 Events.On 站点）：
//   ┌──────────────────────────┬─────────────────────────────┬──────────────────┐
//   │ 事件                     │ 处理方                      │ 集中化状态       │
//   ├──────────────────────────┼─────────────────────────────┼──────────────────┤
//   │ window:maximised         │ app handler                 │ 已迁移至本模块   │
//   │ settings:changed         │ app handler                 │ 已迁移至本模块   │
//   │ project:removed          │ app handler                 │ 已迁移至本模块   │
//   │ workspace:changed        │ workspace authority         │ 已迁移至本模块   │
//   │ ai:apply-to-editor       │ editor.requestApplyToEditor │ 已迁移至本模块   │
//   │ ai:chunk/done/error/...  │ ai.ensureEventListeners     │ 本模块统一编排     │
//   │ terminal:output/exited   │ terminal.ensureEventListener│ TODO: 迁移至本模块 │
//   │ file:saved (workflows)   │ workflows.initWorkflowTriggers│ TODO: 迁移至本模块 │
//   │ workflow:completed       │ workflows.initWorkflowTriggers│ TODO: 迁移至本模块 │
// Koyori IDE 模块 · Cross Window Sync。
// 喵，这是 Koyori IDE 的 Cross Window Sync 模块（前端实现）~
//   │ file:saved (testExplorer)│ testExplorer.initContinuousTesting│ TODO: 迁移至本模块 │
//   │ agent:pending-updated    │ agent.initAgentPendingSync  │ 本模块统一编排     │
//   │ conversation:saved      │ AI store + local subscribers│ 已迁移至本模块   │
//   │ ai:selection             │ local subscribers           │ 已迁移至本模块   │
//   │ ai-window:maximised      │ local subscribers           │ 已迁移至本模块   │
//   └──────────────────────────┴─────────────────────────────┴──────────────────┘
//
// 注：store 仍拥有依赖私有状态的事件处理器；本模块拥有应用主路径的注册与注销
// 时机。这样既避免暴露 pendingAssistantMessage 等内部状态，也确保 bootstrap、
// HMR 和窗口卸载只有一条对称生命周期路径。

import { Events } from "@wailsio/runtime";
import { requestApplyToEditor } from "@/stores/editor";
import { notifyError } from "@/lib/notifications";
import { translate } from "@/lib/i18n";
import {
  beginExtensionLifecycleHold,
  deactivateExtension,
  invalidateExtensionCaches,
  isExtensionActivated,
  refreshExtensionCaches,
  reactivateExtension,
  releaseExtensionLifecycleHold,
  restoreExtensionContributions,
} from "@/lib/vscodeExtensionActivation";
import type {
  ExtensionLifecycleRequest,
  ExtensionLifecycleResult,
} from "@/types";
import {
  handleProjectRemovedEvent,
  handleSettingsChangedEvent,
  handleWindowMaximisedEvent,
  initWindowMaximiseListener,
  initSettingsSyncListener,
  initProjectRemovedListener,
  unregisterAppListeners,
} from "@/stores/app";
import {
  handleWorkspaceChangedEvent,
  syncWorkspaceSnapshot,
} from "@/stores/workspaceStore";
import {
  cleanupAIEventListeners,
  ensureAIEventListeners,
  handleAIChunkEvent,
  handleAIDoneEvent,
  handleAIErrorEvent,
  handleAIStreamBusyEvent,
  handleAIToolCallsEvent,
  handleConversationSavedEvent,
} from "@/stores/ai";
import {
  cleanupAgentPendingSyncListener,
  handleAgentPendingUpdatedEvent,
  initAgentPendingSyncListener,
} from "@/stores/agent";

const eventCancellers: Array<() => void> = [];
let initialised = false;
let listenerGeneration = 0;

type LocalEventName =
  | "conversation:saved"
  | "ai:selection"
  | "ai-window:maximised"
  | "ai:open-settings";
type LocalEventHandler = (event: unknown) => void;
const localEventHandlers = new Map<LocalEventName, Set<LocalEventHandler>>();

export function subscribeCrossWindowEvent(
  name: LocalEventName,
  handler: LocalEventHandler,
): () => void {
  let handlers = localEventHandlers.get(name);
  if (!handlers) {
    handlers = new Set();
    localEventHandlers.set(name, handlers);
  }
  handlers.add(handler);
  return () => handlers?.delete(handler);
}

function dispatchLocalEvent(name: LocalEventName, event: unknown): void {
  for (const handler of localEventHandlers.get(name) ?? []) handler(event);
}

function registerEvent(
  name: string,
  handler: (event: unknown) => void,
  generation: number,
): void {
  const cancel = Events.On(name, (event: unknown) => {
    if (!initialised || generation !== listenerGeneration) return;
    handler(event);
  });
  if (typeof cancel === "function") eventCancellers.push(cancel);
}

interface LifecycleRuntimeState {
  queues: Map<string, Promise<void>>;
  completed: Map<string, ExtensionLifecycleResult>;
  inflight: Map<string, {
    request: ExtensionLifecycleRequest;
    result: Promise<ExtensionLifecycleResult>;
  }>;
}

const lifecycleRuntime = ((globalThis as typeof globalThis & {
  __koyoriIdeExtensionLifecycle?: LifecycleRuntimeState;
}).__koyoriIdeExtensionLifecycle ??= {
  queues: new Map(),
  completed: new Map(),
  inflight: new Map(),
});

// Request IDs are generated by the backend and should not keep renderer memory
// alive indefinitely if a host retries old events after a long session.
const MAX_COMPLETED_LIFECYCLE_REQUESTS = 256;

function pruneCompletedLifecycleResults(): void {
  while (lifecycleRuntime.completed.size > MAX_COMPLETED_LIFECYCLE_REQUESTS) {
    const oldest = lifecycleRuntime.completed.keys().next().value;
    if (typeof oldest !== "string") return;
    lifecycleRuntime.completed.delete(oldest);
  }
}

function lifecyclePayload(event: unknown): ExtensionLifecycleRequest | undefined {
  const raw = (event as { data?: unknown } | null)?.data;
  const value = Array.isArray(raw) ? raw[0] : raw;
  if (!value || typeof value !== "object") return undefined;
  const request = value as Partial<ExtensionLifecycleRequest>;
  if (
    typeof request.requestId !== "string" ||
    request.requestId.trim() === "" ||
    typeof request.extensionId !== "string" ||
    request.extensionId.trim() === "" ||
    typeof request.publisher !== "string" ||
    request.publisher.trim() === "" ||
    typeof request.name !== "string" ||
    request.name.trim() === "" ||
    request.extensionId !== `${request.publisher}.${request.name}` ||
    !["stop", "restore", "invalidate", "commit"].includes(request.action ?? "") ||
    typeof request.wasActive !== "boolean"
  ) {
    return undefined;
  }
  return request as ExtensionLifecycleRequest;
}

function emitLifecycleResult(result: ExtensionLifecycleResult): void {
  void Events.Emit("extension:lifecycle-result", result);
}

async function performExtensionLifecycle(request: ExtensionLifecycleRequest): Promise<ExtensionLifecycleResult> {
  const base = {
    requestId: request.requestId,
    extensionId: request.extensionId,
    publisher: request.publisher,
    name: request.name,
    action: request.action,
    wasActive: request.wasActive,
  } as const;

  try {
    if (request.action === "stop") {
      beginExtensionLifecycleHold(request.extensionId);
      const wasActive = isExtensionActivated(request.extensionId);
      try {
        await deactivateExtension(request.extensionId);
      } catch (stopError) {
        releaseExtensionLifecycleHold(request.extensionId);
        try {
          if (wasActive) {
            const reactivated = await reactivateExtension(request.extensionId);
            if (!reactivated) {
              throw new Error(`Extension reactivation failed: ${request.extensionId}`);
            }
          } else {
            restoreExtensionContributions(request.extensionId);
          }
        } catch (restoreError) {
          beginExtensionLifecycleHold(request.extensionId);
          throw new Error(
            `${stopError instanceof Error ? stopError.message : String(stopError)}; ` +
              `restoring the old extension failed: ${restoreError instanceof Error ? restoreError.message : String(restoreError)}`,
          );
        }
        throw stopError;
      }
      return { ...base, ok: true, wasActive };
    }

    if (request.action === "restore") {
      await refreshExtensionCaches(request.publisher, request.name);
      releaseExtensionLifecycleHold(request.extensionId);
      if (request.wasActive) {
        let reactivated = false;
        try {
          reactivated = await reactivateExtension(request.extensionId);
        } catch (error) {
          beginExtensionLifecycleHold(request.extensionId);
          throw error;
        }
        if (!reactivated) {
          beginExtensionLifecycleHold(request.extensionId);
          throw new Error(`Extension reactivation failed: ${request.extensionId}`);
        }
      }
      if (!request.wasActive) restoreExtensionContributions(request.extensionId);
      return { ...base, ok: true };
    }

    if (request.action === "commit") {
      await refreshExtensionCaches(request.publisher, request.name);
      releaseExtensionLifecycleHold(request.extensionId);
      return { ...base, ok: true };
    }

    invalidateExtensionCaches(request.extensionId);
    releaseExtensionLifecycleHold(request.extensionId);
    return { ...base, ok: true };
  } catch (error) {
    return {
      ...base,
      ok: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

function handleExtensionLifecycleRequest(event: unknown): void {
  const request = lifecyclePayload(event);
  if (!request) return;
  const completed = lifecycleRuntime.completed.get(request.requestId);
  if (completed) {
    if (
      completed.extensionId === request.extensionId &&
      completed.publisher === request.publisher &&
      completed.name === request.name &&
      completed.action === request.action
    ) {
      emitLifecycleResult(completed);
    }
    return;
  }

  const inflight = lifecycleRuntime.inflight.get(request.requestId);
  if (inflight) {
    // The first copy owns execution and emission. A duplicate retry must not
    // run a second stop/restore operation while the first one is queued.
    if (
      inflight.request.extensionId === request.extensionId &&
      inflight.request.publisher === request.publisher &&
      inflight.request.name === request.name &&
      inflight.request.action === request.action
    ) {
      return;
    }
    return;
  }

  const previous = lifecycleRuntime.queues.get(request.extensionId) ?? Promise.resolve();
  const work: Promise<ExtensionLifecycleResult> = previous
    .catch(() => undefined)
    .then(() => performExtensionLifecycle(request));
  lifecycleRuntime.inflight.set(request.requestId, { request, result: work });
  void work
    .then((result) => {
      lifecycleRuntime.completed.set(request.requestId, result);
      pruneCompletedLifecycleResults();
      emitLifecycleResult(result);
    })
    .catch((error: unknown) => {
      const result: ExtensionLifecycleResult = {
        requestId: request.requestId,
        extensionId: request.extensionId,
        publisher: request.publisher,
        name: request.name,
        action: request.action,
        wasActive: request.wasActive,
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
      lifecycleRuntime.completed.set(request.requestId, result);
      pruneCompletedLifecycleResults();
      emitLifecycleResult(result);
    })
    .finally(() => {
      if (lifecycleRuntime.inflight.get(request.requestId)?.result === work) {
        lifecycleRuntime.inflight.delete(request.requestId);
      }
    });
  const queued = work.then(() => undefined, () => undefined);
  lifecycleRuntime.queues.set(request.extensionId, queued);
  void queued.finally(() => {
    if (lifecycleRuntime.queues.get(request.extensionId) === queued) {
      lifecycleRuntime.queues.delete(request.extensionId);
    }
  });
}

/**
 * 处理 AI 伴侣窗口发出的「应用到编辑器」事件。打开目标文件并弹出 Diff
 * 预览，待用户确认后再写入。从 main.ts 迁移至此，使本模块成为此事件唯一
 * 的 Events.On 注册点。
 *
 * payload 形如 { code, filePath, language }；filePath 必须由发送方携带
 * （CodeEditor 选中发送时缓存路径），缺失则提示错误而非静默写空路径。
 */
export function handleApplyToEditorEvent(event: unknown): void {
  const raw = (event as { data?: unknown } | null)?.data;
  const payload = (Array.isArray(raw) ? raw[0] : raw) as
    | { code?: string; filePath?: string; language?: string }
    | undefined;
  if (!payload?.code) return;
  const path = (payload.filePath || "").trim();
  if (!path) {
    notifyError(translate("aiWindow.noActiveFile"), translate("aiWindow.applyTitle"));
    return;
  }
  void requestApplyToEditor(path, payload.code);
}

/**
 * 在应用启动时一次性接线所有跨窗口事件 → store 动作映射。幂等：重复调用
 * 会先 teardown 旧监听器再重新注册（HMR / 多次 bootstrap 场景）。
 *
 * - app.ts 三个处理器：编排调用其 init 函数，再由本模块注册 Events.On。
 * - ai:apply-to-editor：从 main.ts 迁移至此，由本模块统一注册 Events.On。
 *   仅在主窗口（非 /ai-window 路由）注册，避免 AI 窗口自身重复处理。
 */
export function initCrossWindowSync(): void {
  // 幂等：若已初始化，先清理再重注册。
  if (initialised) {
    teardownCrossWindowSync();
  }

  // app.ts 三个监听器：编排调用其 init 函数。
  initWindowMaximiseListener();
  initSettingsSyncListener();
  initProjectRemovedListener();
  ensureAIEventListeners();
  initAgentPendingSyncListener();
  initialised = true;
  const generation = ++listenerGeneration;

  try {
    registerEvent("window:maximised", handleWindowMaximisedEvent, generation);
    registerEvent("settings:changed", handleSettingsChangedEvent, generation);
    registerEvent("project:removed", handleProjectRemovedEvent, generation);
    registerEvent("workspace:changed", handleWorkspaceChangedEvent, generation);
    registerEvent("ai:chunk", handleAIChunkEvent, generation);
    registerEvent("ai:done", handleAIDoneEvent, generation);
    registerEvent("ai:error", handleAIErrorEvent, generation);
    registerEvent("ai:stream-busy", handleAIStreamBusyEvent, generation);
    registerEvent("ai:tool_calls", handleAIToolCallsEvent, generation);
    registerEvent("conversation:saved", (event) => {
      handleConversationSavedEvent(event);
      dispatchLocalEvent("conversation:saved", event);
    }, generation);
    registerEvent("agent:pending-updated", handleAgentPendingUpdatedEvent, generation);
    registerEvent("ai:selection", (event) => dispatchLocalEvent("ai:selection", event), generation);
    registerEvent(
      "ai:open-settings",
      (event) => dispatchLocalEvent("ai:open-settings", event),
      generation,
    );
    registerEvent(
      "ai-window:maximised",
      (event) => dispatchLocalEvent("ai-window:maximised", event),
      generation,
    );
    if (!window.location.hash.includes("ai-window")) {
      registerEvent("ai:apply-to-editor", handleApplyToEditorEvent, generation);
    }
    registerEvent(
      "extension:lifecycle-request",
      handleExtensionLifecycleRequest,
      generation,
    );
    void syncWorkspaceSnapshot().catch((error) => {
      console.warn("[workspace] initial backend snapshot failed", error);
    });
  } catch {
    teardownCrossWindowSync();
  }
}

/**
 * 注销本模块注册的所有监听器。app.ts 的三个监听器通过 unregisterAppListeners
 * 统一注销；ai:apply-to-editor 的 cancel 在此直接清理。用于 HMR / 测试清理。
 */
export function teardownCrossWindowSync(): void {
  initialised = false;
  listenerGeneration += 1;
  cleanupAgentPendingSyncListener();
  cleanupAIEventListeners();
  unregisterAppListeners();
  for (const cancel of eventCancellers.splice(0)) {
    try { cancel(); } catch { /* ignore */ }
  }
}

import.meta.hot?.dispose(teardownCrossWindowSync);

/** 测试用：返回本模块是否已初始化。 */
export function isCrossWindowSyncInitialised(): boolean {
  return initialised;
}
