import { flushPromises, mount } from "@vue/test-utils";
import { beforeEach, describe, expect, it, vi } from "vitest";

const runtime = vi.hoisted(() => ({
  byID: vi.fn(),
}));

const ui = vi.hoisted(() => ({
  confirm: vi.fn(),
  prompt: vi.fn(),
  success: vi.fn(),
  error: vi.fn(),
  info: vi.fn(),
  revealInOS: vi.fn(),
}));

vi.mock("@wailsio/runtime", () => ({
  Call: { ByID: runtime.byID },
}));

vi.mock("element-plus", () => ({
  ElMessage: {
    success: ui.success,
    error: ui.error,
    info: ui.info,
  },
  ElMessageBox: {
    confirm: ui.confirm,
    prompt: ui.prompt,
  },
}));

vi.mock("@/lib/i18n", () => ({
  useI18n: () => ({
    locale: { value: "en" },
    t: (key: string, params?: Record<string, string | number>) => {
      if (!params) return key;
      return `${key}:${Object.values(params).join(":")}`;
    },
  }),
}));

vi.mock("@/api/services", () => ({
  fileService: { revealInOS: ui.revealInOS },
}));

import {
  addWorktree,
  gitWorktreeState,
  loadWorktrees,
  lockWorktree,
  moveWorktree,
  pruneWorktrees,
  removeWorktree,
  resetGitWorktreeStore,
  setGitWorktreeServiceBindings,
  unlockWorktree,
  useGitWorktreeStore,
  wailsGitWorktreeService,
  type GitWorktreeServiceBindings,
  type WorktreeInfo,
} from "./gitWorktree";
import WorktreePanel from "@/components/git/WorktreePanel.vue";

const fixture: WorktreeInfo = {
  path: "C:\\repo",
  head: "1234567890abcdef",
  branch: "main",
  bare: false,
};

function deferred<T>() {
  let resolve!: (value: T) => void;
  let reject!: (reason?: unknown) => void;
  const promise = new Promise<T>((resolvePromise, rejectPromise) => {
    resolve = resolvePromise;
    reject = rejectPromise;
  });
  return { promise, resolve, reject };
}

function createService(): GitWorktreeServiceBindings {
  return {
    ListWorktrees: vi.fn(async () => [fixture]),
    AddWorktree: vi.fn(async () => undefined),
    RemoveWorktree: vi.fn(async () => undefined),
    PruneWorktrees: vi.fn(async () => []),
    LockWorktree: vi.fn(async () => undefined),
    UnlockWorktree: vi.fn(async () => undefined),
    MoveWorktree: vi.fn(async () => undefined),
  };
}

describe("gitWorktree Wails bindings", () => {
  beforeEach(() => {
    resetGitWorktreeStore();
    runtime.byID.mockReset();
    runtime.byID.mockResolvedValue(undefined);
  });

  it("calls every backend method with the generated-binding argument shape", async () => {
    runtime.byID.mockResolvedValueOnce([fixture]);
    await wailsGitWorktreeService.ListWorktrees("C:\\repo");
    await wailsGitWorktreeService.AddWorktree(
      "C:\\repo",
      "C:\\repo\\wt",
      "main",
      { detach: false },
    );
    await wailsGitWorktreeService.RemoveWorktree("C:\\repo", "C:\\repo\\wt", true);
    await wailsGitWorktreeService.PruneWorktrees("C:\\repo", true);
    await wailsGitWorktreeService.LockWorktree("C:\\repo", "C:\\repo\\wt", "reason");
    await wailsGitWorktreeService.UnlockWorktree("C:\\repo", "C:\\repo\\wt");
    const move = wailsGitWorktreeService.MoveWorktree;
    expect(move).toBeTypeOf("function");
    if (!move) throw new Error("MoveWorktree binding is missing");
    await move(
      "C:\\repo",
      "C:\\repo\\wt",
      "C:\\repo\\moved",
      false,
      false,
    );

    // Method IDs are generated by the pinned Wails CLI and are intentionally
    // not duplicated in tests. Assert the generated call shape and leave ID
    // ownership to the generated binding tree plus its drift gate.
    expect(runtime.byID.mock.calls).toHaveLength(7);
    expect(runtime.byID.mock.calls.map((call) => call.slice(1))).toEqual([
      ["C:\\repo"],
      ["C:\\repo", "C:\\repo\\wt", "main", { detach: false }],
      ["C:\\repo", "C:\\repo\\wt", true],
      ["C:\\repo", true],
      ["C:\\repo", "C:\\repo\\wt", "reason"],
      ["C:\\repo", "C:\\repo\\wt"],
      ["C:\\repo", "C:\\repo\\wt", "C:\\repo\\moved", false],
    ]);
    expect(runtime.byID.mock.calls.every(([methodId]) =>
      typeof methodId === "number" && methodId >= 0,
    )).toBe(true);
  });
});

describe("gitWorktree store", () => {
  let service: GitWorktreeServiceBindings;

  beforeEach(() => {
    resetGitWorktreeStore();
    service = createService();
    setGitWorktreeServiceBindings(service);
  });

  it("loads worktrees and exposes a stable singleton store", async () => {
    const first = useGitWorktreeStore();
    const second = useGitWorktreeStore();
    expect(first).toBe(second);

    const result = await first.loadWorktrees("C:\\repo");

    expect(result).toEqual([fixture]);
    expect(first.worktrees).toEqual([fixture]);
    expect(first.repoPath).toBe("C:\\repo");
    expect(first.loading).toBe(false);
    expect(first.error).toBeNull();
  });

  it("ignores a stale list result after the repository changes", async () => {
    const oldRequest = deferred<WorktreeInfo[]>();
    const newRequest = deferred<WorktreeInfo[]>();
    const list = vi.mocked(service.ListWorktrees);
    list.mockImplementation((repoPath) => (
      repoPath === "C:\\old" ? oldRequest.promise : newRequest.promise
    ));

    const oldLoad = loadWorktrees("C:\\old");
    const newLoad = loadWorktrees("C:\\new");
    const current = { ...fixture, path: "C:\\new", branch: "feature" };
    newRequest.resolve([current]);
    await newLoad;
    oldRequest.resolve([{ ...fixture, path: "C:\\old" }]);
    await oldLoad;

    expect(gitWorktreeState.repoPath).toBe("C:\\new");
    expect(gitWorktreeState.worktrees).toEqual([current]);
    expect(gitWorktreeState.loading).toBe(false);
  });

  it("clears stale mutation activity when the repository changes", async () => {
    const oldMutation = deferred<void>();
    vi.mocked(service.AddWorktree).mockReturnValueOnce(oldMutation.promise);

    const pendingAdd = addWorktree("C:\\old", "C:\\old\\worktree", "main");
    expect(gitWorktreeState.mutating).toBe(true);

    await loadWorktrees("C:\\new");
    expect(gitWorktreeState.repoPath).toBe("C:\\new");
    expect(gitWorktreeState.mutating).toBe(false);

    oldMutation.resolve(undefined);
    await pendingAdd;
    expect(gitWorktreeState.repoPath).toBe("C:\\new");
    expect(gitWorktreeState.mutating).toBe(false);
  });

  it("runs every mutation and refreshes state after non-preview operations", async () => {
    await loadWorktrees("C:\\repo");
    const list = vi.mocked(service.ListWorktrees);
    list.mockClear();

    await addWorktree("C:\\repo", "C:\\repo\\wt", "main", {
      newBranch: "feature/worktree",
      detach: false,
      force: true,
      noCheckout: true,
    });
    await removeWorktree("C:\\repo", "C:\\repo\\wt", false);
    vi.mocked(service.PruneWorktrees).mockResolvedValueOnce([" stale ", ""]);
    await expect(pruneWorktrees("C:\\repo", true)).resolves.toEqual(["stale"]);
    await pruneWorktrees("C:\\repo", false);
    await lockWorktree("C:\\repo", "C:\\repo\\wt", "maintenance");
    await unlockWorktree("C:\\repo", "C:\\repo\\wt");
    await moveWorktree("C:\\repo", "C:\\repo\\wt", "C:\\repo\\moved", true);

    expect(service.AddWorktree).toHaveBeenCalledWith(
      "C:\\repo",
      "C:\\repo\\wt",
      "main",
      {
        newBranch: "feature/worktree",
        detach: false,
        force: true,
        noCheckout: true,
        allowOutsideRepository: false,
      },
    );
    expect(service.RemoveWorktree).toHaveBeenCalledWith(
      "C:\\repo",
      "C:\\repo\\wt",
      false,
    );
    expect(service.PruneWorktrees).toHaveBeenNthCalledWith(1, "C:\\repo", true);
    expect(service.PruneWorktrees).toHaveBeenNthCalledWith(2, "C:\\repo", false);
    expect(service.LockWorktree).toHaveBeenCalledWith(
      "C:\\repo",
      "C:\\repo\\wt",
      "maintenance",
    );
    expect(service.UnlockWorktree).toHaveBeenCalledWith("C:\\repo", "C:\\repo\\wt");
    expect(service.MoveWorktree).toHaveBeenCalledWith(
      "C:\\repo",
      "C:\\repo\\wt",
      "C:\\repo\\moved",
      true,
      false,
    );
    expect(list).toHaveBeenCalledTimes(6);
    expect(gitWorktreeState.mutating).toBe(false);
  });

  it("passes explicit authorization for an external move", async () => {
    await loadWorktrees("C:\\repo");
    const list = vi.mocked(service.ListWorktrees);
    list.mockClear();

    await moveWorktree(
      "C:\\repo",
      "C:\\repo\\wt",
      "D:\\outside-moved",
      false,
      true,
    );

    expect(service.MoveWorktree).toHaveBeenCalledWith(
      "C:\\repo",
      "C:\\repo\\wt",
      "D:\\outside-moved",
      false,
      true,
    );
    expect(list).toHaveBeenCalledOnce();
  });
  it("records and rethrows async failures while resetting activity flags", async () => {
    vi.mocked(service.ListWorktrees).mockRejectedValueOnce(new Error("list failed"));
    await expect(loadWorktrees("C:\\repo")).rejects.toThrow("list failed");
    expect(gitWorktreeState.loading).toBe(false);
    expect(gitWorktreeState.error).toBe("list failed");

    vi.mocked(service.RemoveWorktree).mockRejectedValueOnce(new Error("remove failed"));
    await expect(removeWorktree("C:\\repo", "C:\\repo\\wt", false))
      .rejects.toThrow("remove failed");
    expect(gitWorktreeState.mutating).toBe(false);
    expect(gitWorktreeState.error).toBe("remove failed");
  });

  it("rejects blank required paths before invoking the backend", async () => {
    await expect(addWorktree("C:\\repo", "  ", "HEAD")).rejects.toThrow(
      "worktree path is required",
    );
    await expect(moveWorktree("C:\\repo", "C:\\repo\\wt", " ")).rejects.toThrow(
      "new worktree path is required",
    );
    expect(service.AddWorktree).not.toHaveBeenCalled();
    expect(service.MoveWorktree).not.toHaveBeenCalled();
  });

  it("passes an explicit authorization after confirming an external add path", async () => {
    const wrapper = mount(WorktreePanel, {
      props: {
        repoPath: "C:\\repo",
        branches: ["main"],
        service,
        revealService: null,
      },
    });
    await flushPromises();

    await wrapper.get('[aria-label="worktree.addAria"]').trigger("click");
    await wrapper.get('[aria-label="worktree.pathAria"]').setValue("D:\\outside-worktree");
    await wrapper.get(".worktree-panel__form").trigger("submit");
    await flushPromises();

    expect(ui.confirm).toHaveBeenCalledOnce();
    expect(service.AddWorktree).toHaveBeenCalledWith(
      "C:\\repo",
      "D:\\outside-worktree",
      "main",
      {
        newBranch: "",
        detach: false,
        force: false,
        allowOutsideRepository: true,
      },
    );
    wrapper.unmount();
  });
});

describe("WorktreePanel complete workflow", () => {
  let service: GitWorktreeServiceBindings;

  beforeEach(() => {
    service = createService();
    ui.confirm.mockReset().mockResolvedValue("confirm");
    ui.prompt.mockReset().mockResolvedValue({ value: "C:\\repo\\moved" });
    ui.success.mockReset();
    ui.error.mockReset();
    ui.info.mockReset();
    ui.revealInOS.mockReset().mockResolvedValue(undefined);
  });

  it("renders an accessible table and supports move, force removal, and prune preview", async () => {
    const linkedFixture = { ...fixture, path: "C:\\repo\\linked" };
    vi.mocked(service.ListWorktrees).mockResolvedValue([fixture, linkedFixture]);
    const wrapper = mount(WorktreePanel, {
      props: {
        repoPath: "C:\\repo",
        branches: ["main"],
        service,
        revealService: null,
      },
    });
    await flushPromises();

    expect(wrapper.get('[role="table"]').attributes("aria-label")).toBe(
      "worktree.listAria",
    );
    expect(wrapper.findAll('[role="columnheader"]')).toHaveLength(5);
    expect(wrapper.findAll('[role="columnheader"]')[2].text()).toBe(
      "worktree.head",
    );
    expect(wrapper.findAll(".worktree-panel__row")).toHaveLength(2);
    expect(wrapper.text()).toContain("12345678");

    let linkedRow = wrapper.findAll(".worktree-panel__row")[1];
    await linkedRow.get('button[title="worktree.move"]').trigger("click");
    await flushPromises();
    expect(service.MoveWorktree).toHaveBeenCalledWith(
      "C:\\repo",
      "C:\\repo\\linked",
      "C:\\repo\\moved",
      false,
      false,
    );

    linkedRow = wrapper.findAll(".worktree-panel__row")[1];
    await linkedRow.get('button[title="worktree.remove"]').trigger("click");
    await flushPromises();
    const dialog = wrapper.get('[role="dialog"]');
    expect(dialog.text()).toContain("C:\\repo");
    for (const button of dialog.findAll("button")) {
      expect(button.attributes("aria-label")).toBeTruthy();
    }
    await dialog.get('input[type="checkbox"]').setValue(true);
    await dialog.get(".worktree-panel__command--danger").trigger("click");
    await flushPromises();
    expect(service.RemoveWorktree).toHaveBeenCalledWith(
      "C:\\repo",
      "C:\\repo\\linked",
      true,
    );

    vi.mocked(service.PruneWorktrees).mockResolvedValueOnce([
      "worktrees/stale: directory is missing",
    ]);
    await wrapper.get('[aria-label="worktree.pruneAria"]').trigger("click");
    await flushPromises();
    expect(service.PruneWorktrees).toHaveBeenNthCalledWith(1, "C:\\repo", true);
    expect(service.PruneWorktrees).toHaveBeenNthCalledWith(2, "C:\\repo", false);
    expect(ui.confirm).toHaveBeenCalledWith(
      expect.stringContaining("worktrees/stale"),
      "worktree.pruneTitle",
      expect.objectContaining({ type: "warning" }),
    );

    wrapper.unmount();
  });

  it("confirms an external move and keeps authorization for a force retry", async () => {
    const linkedFixture = { ...fixture, path: "C:\\repo\\linked" };
    vi.mocked(service.ListWorktrees).mockResolvedValue([fixture, linkedFixture]);
    const move = service.MoveWorktree;
    if (!move) throw new Error("MoveWorktree binding is missing");
    vi.mocked(move)
      .mockRejectedValueOnce(new Error("dirty worktree"))
      .mockResolvedValueOnce(undefined);
    ui.prompt.mockResolvedValueOnce({ value: "D:\\outside-moved" });

    const wrapper = mount(WorktreePanel, {
      props: {
        repoPath: "C:\\repo",
        branches: ["main"],
        service,
        revealService: null,
      },
    });
    await flushPromises();

    await wrapper.findAll(".worktree-panel__row")[1]
      .get('button[title="worktree.move"]')
      .trigger("click");
    await flushPromises();

    expect(ui.confirm).toHaveBeenNthCalledWith(
      1,
      "worktree.outsideMoveConfirm:D:\\outside-moved:C:\\repo",
      "worktree.move",
      {
        confirmButtonText: "worktree.move",
        cancelButtonText: "worktree.cancel",
        type: "warning",
      },
    );
    expect(ui.confirm).toHaveBeenNthCalledWith(
      2,
      expect.stringContaining("worktree.forceMoveConfirm"),
      "worktree.move",
      expect.objectContaining({ type: "warning" }),
    );
    expect(service.MoveWorktree).toHaveBeenNthCalledWith(
      1,
      "C:\\repo",
      "C:\\repo\\linked",
      "D:\\outside-moved",
      false,
      true,
    );
    expect(service.MoveWorktree).toHaveBeenNthCalledWith(
      2,
      "C:\\repo",
      "C:\\repo\\linked",
      "D:\\outside-moved",
      true,
      true,
    );
    wrapper.unmount();
  });

  it("does not move outside the repository when authorization is canceled", async () => {
    const linkedFixture = { ...fixture, path: "C:\\repo\\linked" };
    vi.mocked(service.ListWorktrees).mockResolvedValue([fixture, linkedFixture]);
    ui.prompt.mockResolvedValueOnce({ value: "D:\\outside-moved" });
    ui.confirm.mockRejectedValueOnce("cancel");

    const wrapper = mount(WorktreePanel, {
      props: {
        repoPath: "C:\\repo",
        branches: ["main"],
        service,
        revealService: null,
      },
    });
    await flushPromises();

    await wrapper.findAll(".worktree-panel__row")[1]
      .get('button[title="worktree.move"]')
      .trigger("click");
    await flushPromises();

    expect(ui.confirm).toHaveBeenCalledWith(
      "worktree.outsideMoveConfirm:D:\\outside-moved:C:\\repo",
      "worktree.move",
      expect.objectContaining({ type: "warning" }),
    );
    expect(service.MoveWorktree).not.toHaveBeenCalled();
    wrapper.unmount();
  });
  it("disables linked-only mutations for the main and bare worktrees", async () => {
    const linked = { ...fixture, path: "C:\\repo\\linked", branch: "feature" };
    vi.mocked(service.ListWorktrees).mockResolvedValue([
      fixture,
      { ...fixture, path: "C:\\bare.git", bare: true },
      linked,
    ]);
    const wrapper = mount(WorktreePanel, {
      props: {
        repoPath: linked.path,
        branches: ["main"],
        service,
        revealService: null,
      },
    });
    await flushPromises();

    const rows = wrapper.findAll(".worktree-panel__row");
    expect(rows).toHaveLength(3);
    for (const row of rows) {
      expect(row.get<HTMLButtonElement>('button[title="worktree.open"]').element.disabled)
        .toBe(false);
    }
    for (const row of rows.slice(0, 2)) {
      expect(row.get<HTMLButtonElement>('button[title="worktree.lock"]').element.disabled)
        .toBe(true);
      expect(row.get<HTMLButtonElement>('button[title="worktree.move"]').element.disabled)
        .toBe(true);
      expect(row.get<HTMLButtonElement>('button[title="worktree.remove"]').element.disabled)
        .toBe(true);
    }
    expect(rows[2].get<HTMLButtonElement>('button[title="worktree.lock"]').element.disabled)
      .toBe(false);
    expect(rows[2].get<HTMLButtonElement>('button[title="worktree.move"]').element.disabled)
      .toBe(true);
    expect(rows[2].get<HTMLButtonElement>('button[title="worktree.remove"]').element.disabled)
      .toBe(true);
    wrapper.unmount();
  });

  it("matches current UNC worktrees without case sensitivity", async () => {
    vi.mocked(service.ListWorktrees).mockResolvedValue([
      { ...fixture, path: "\\\\Server\\Share\\Repo-Main" },
      { ...fixture, path: "\\\\SERVER\\SHARE\\REPO-LINKED", branch: "feature" },
    ]);
    const wrapper = mount(WorktreePanel, {
      props: {
        repoPath: "\\\\server\\share\\repo-linked",
        branches: ["main"],
        service,
        revealService: null,
      },
    });
    await flushPromises();

    const linkedRow = wrapper.findAll(".worktree-panel__row")[1];
    expect(linkedRow.get<HTMLButtonElement>('button[title="worktree.lock"]').element.disabled)
      .toBe(false);
    expect(linkedRow.get<HTMLButtonElement>('button[title="worktree.move"]').element.disabled)
      .toBe(true);
    expect(linkedRow.get<HTMLButtonElement>('button[title="worktree.remove"]').element.disabled)
      .toBe(true);
    wrapper.unmount();
  });

  it("does not prune the old repository after confirmation context changes", async () => {
    const confirmation = deferred<string>();
    ui.confirm.mockReturnValueOnce(confirmation.promise);
    vi.mocked(service.PruneWorktrees).mockResolvedValueOnce(["stale-entry"]);
    const wrapper = mount(WorktreePanel, {
      props: {
        repoPath: "C:\\old",
        branches: ["main"],
        service,
        revealService: null,
      },
    });
    await flushPromises();

    await wrapper.get('[aria-label="worktree.pruneAria"]').trigger("click");
    await flushPromises();
    await wrapper.setProps({ repoPath: "C:\\new" });
    confirmation.resolve("confirm");
    await flushPromises();

    expect(service.PruneWorktrees).toHaveBeenCalledTimes(1);
    expect(service.PruneWorktrees).toHaveBeenCalledWith("C:\\old", true);
    wrapper.unmount();
  });
});
